HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 989
ETag: W/"3dd-g5Ni+YtgFR9TrdNrRVXo3grBB9E"
Date: Wed, 12 Apr 2023 10:09:11 GMT
Connection: close

{"newAds":[{"_data":{"id":"23852977502550575"},"_fields":["account_id","ad_review_feedback","adlabels","adset","adset_id","bid_amount","bid_info","bid_type","campaign","campaign_id","configured_status","conversion_domain","conversion_specs","created_time","creative","demolink_hash","display_sequence","effective_status","engagement_audience","failed_delivery_checks","id","issues_info","last_updated_by_app_id","name","preview_shareable_link","priority","recommendations","source_ad","source_ad_id","status","targeting","tracking_and_conversion_with_defaults","tracking_specs","updated_time"],"_changes":{"id":"23852977502550575"},"id":"23852977502550575","_api":{"accessToken":"EAAe9FnaGY5gBADGCKmZA2cyXuRNaG8j8cj6wqZBW55Jtf1TtDXcZB10V0iwoOGKTie6K5oNZAyBAPg3JlUFvjrz7Up4LqYvw46RNZC974OJ1D6VUO8O0ZADeuZBtIQEN1T7VPxIEfwVpNiNV9OWAQH59qOwGV5AYNSbU0PE4ZAr4T0ZBVWGUb4GN4szgz4JIBWkU7bqyU0CpRkxQ59iUk5bqqvE4ZBZAmFLCixrfQq7Sh5pqaUuZBdTNzi6y","locale":"en_US","_debug":true,"_showHeader":false}}]}